const {
  VITE_AUTH0_DOMAIN,
  VITE_AUTH0_CLIENT_ID,
  VITE_AUTH0_AUDIENCE,
  VITE_AUTH0_SCOPE,
  VITE_AUTH0_REDIRECT_URL,
} = import.meta.env;

export const AUTH0_DOMAIN = VITE_AUTH0_DOMAIN;
export const AUTH0_CLIENT_ID = VITE_AUTH0_CLIENT_ID;
export const AUTH0_AUDIENCE = VITE_AUTH0_AUDIENCE;
export const AUTH0_SCOPE = VITE_AUTH0_SCOPE;
export const AUTH0_REDIRECT_URL = VITE_AUTH0_REDIRECT_URL;
