/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AdminMetricTrend } from "./admin-metric-trend";
// May contain unused imports in some cases
// @ts-ignore
import type { AdminPriorityDistribution } from "./admin-priority-distribution";
// May contain unused imports in some cases
// @ts-ignore
import type { AdminWeeklyTrend } from "./admin-weekly-trend";

export interface AdminDashboard {
  total_tasks: AdminMetricTrend;
  active_users: AdminMetricTrend;
  pending_tasks: AdminMetricTrend;
  completed_tasks: AdminMetricTrend;
  weekly_trends: Array<AdminWeeklyTrend>;
  priority_distribution: Array<AdminPriorityDistribution>;
}
