/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `LowEnergyPlanCard` - LowEnergyPlanCard * `TaskTriagePanel` - TaskTriagePanel * `TimeBoxPlanCard` - TimeBoxPlanCard * `TodayPlanCard` - TodayPlanCard
 */

export const ComponentEnum = {
  LowEnergyPlanCard: "LowEnergyPlanCard",
  TaskTriagePanel: "TaskTriagePanel",
  TimeBoxPlanCard: "TimeBoxPlanCard",
  TodayPlanCard: "TodayPlanCard",
} as const;

export type ComponentEnum = (typeof ComponentEnum)[keyof typeof ComponentEnum];
