/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `none` - none * `overdue` - overdue * `due_today` - due_today * `due_soon` - due_soon * `later` - later
 */

export const DueStatusEnum = {
  None: "none",
  Overdue: "overdue",
  DueToday: "due_today",
  DueSoon: "due_soon",
  Later: "later",
} as const;

export type DueStatusEnum = (typeof DueStatusEnum)[keyof typeof DueStatusEnum];
