/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { EnergyLevelEnum } from "./energy-level-enum";
// May contain unused imports in some cases
// @ts-ignore
import type { FocusModeEnum } from "./focus-mode-enum";

export interface EnergyCheckIn {
  id: number;
  date: string;
  energy_level?: EnergyLevelEnum;
  available_minutes?: number;
  focus_mode?: FocusModeEnum;
  context?: string;
  created_at: string;
  updated_at: string;
}
