/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `flexible` - Flexible * `deep` - Deep Work * `admin` - Admin * `light` - Light Work
 */

export const FocusModeEnum = {
  Flexible: "flexible",
  Deep: "deep",
  Admin: "admin",
  Light: "light",
} as const;

export type FocusModeEnum = (typeof FocusModeEnum)[keyof typeof FocusModeEnum];
