/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `default` - default * `limited_time` - limited_time * `low_energy` - low_energy * `overdue_triage` - overdue_triage
 */

export const ModeEnum = {
  Default: "default",
  LimitedTime: "limited_time",
  LowEnergy: "low_energy",
  OverdueTriage: "overdue_triage",
} as const;

export type ModeEnum = (typeof ModeEnum)[keyof typeof ModeEnum];
