/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PriorityEnum } from "./priority-enum";

export interface PatchedTaskAdminRequest {
  title?: string;
  description?: string;
  dtstart?: string | null;
  rrule?: string | null;
  anchor_mode?: PatchedTaskAdminRequestAnchorModeEnum | null;
  due_date?: string | null;
  priority?: PriorityEnum;
  tags?: Array<number>;
  completion_date?: string | null;
  order?: number;
}

export const PatchedTaskAdminRequestAnchorModeEnum = {
  Scheduled: "SCHEDULED",
  Completed: "COMPLETED",
  Empty: "",
} as const;

export type PatchedTaskAdminRequestAnchorModeEnum =
  (typeof PatchedTaskAdminRequestAnchorModeEnum)[keyof typeof PatchedTaskAdminRequestAnchorModeEnum];
