/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DueStatusEnum } from "./due-status-enum";

export interface PlanItemSignals {
  due_date: string | null;
  due_status: DueStatusEnum;
  due_label: string;
  due_in_days: number | null;
  priority: string;
  priority_label: string;
  estimated_minutes: number;
  is_recurring: boolean;
  project_title: string;
  section_title: string | null;
  score: number;
  snoozed_count: number;
  dismissed_count: number;
}
