/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PlanItemSignals } from "./plan-item-signals";
// May contain unused imports in some cases
// @ts-ignore
import type { PlanItemStatusEnum } from "./plan-item-status-enum";
// May contain unused imports in some cases
// @ts-ignore
import type { Task } from "./task";

export interface PlanItem {
  id: number;
  task: Task;
  order: number;
  reason: string;
  estimated_minutes: number;
  score: number;
  signals: PlanItemSignals;
  status: PlanItemStatusEnum;
  snoozed_until: string | null;
  accepted_at: string | null;
  dismissed_at: string | null;
  created_at: string;
  updated_at: string;
}
