/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `suggested` - Suggested * `accepted` - Accepted * `snoozed` - Snoozed * `dismissed` - Dismissed * `done` - Done
 */

export const PlanItemStatusEnum = {
  Suggested: "suggested",
  Accepted: "accepted",
  Snoozed: "snoozed",
  Dismissed: "dismissed",
  Done: "done",
} as const;

export type PlanItemStatusEnum =
  (typeof PlanItemStatusEnum)[keyof typeof PlanItemStatusEnum];
