/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AllowedActionsEnum } from "./allowed-actions-enum";
// May contain unused imports in some cases
// @ts-ignore
import type { ComponentEnum } from "./component-enum";
// May contain unused imports in some cases
// @ts-ignore
import type { ModeEnum } from "./mode-enum";

export interface PlannerUiSchema {
  component: ComponentEnum;
  mode: ModeEnum;
  title: string;
  message: string;
  highlights: Array<string>;
  suggestion_ids: Array<number>;
  allowed_actions: Array<AllowedActionsEnum>;
}
