/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `NONE` - None * `LOW` - Low * `MEDIUM` - Medium * `HIGH` - High
 */

export const PriorityEnum = {
  None: "NONE",
  Low: "LOW",
  Medium: "MEDIUM",
  High: "HIGH",
} as const;

export type PriorityEnum = (typeof PriorityEnum)[keyof typeof PriorityEnum];
