/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProductivitySummary {
  total: number;
  completed: number;
  pending: number;
  overdue: number;
  due_today: number;
  completed_this_week: number;
  created_this_week: number;
  completion_rate: number;
  avg_completion_days: number | null;
}
