/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PriorityEnum } from "./priority-enum";

export interface TaskAdmin {
  id: number;
  title: string;
  description?: string;
  dtstart?: string | null;
  rrule?: string | null;
  anchor_mode?: TaskAdminAnchorModeEnum | null;
  due_date?: string | null;
  priority?: PriorityEnum;
  tags?: Array<number>;
  completion_date?: string | null;
  order?: number;
  project: number;
  created_by: number;
}

export const TaskAdminAnchorModeEnum = {
  Scheduled: "SCHEDULED",
  Completed: "COMPLETED",
  Empty: "",
} as const;

export type TaskAdminAnchorModeEnum =
  (typeof TaskAdminAnchorModeEnum)[keyof typeof TaskAdminAnchorModeEnum];
