/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { EnergyCheckIn } from "./energy-check-in";
// May contain unused imports in some cases
// @ts-ignore
import type { PlanItem } from "./plan-item";
// May contain unused imports in some cases
// @ts-ignore
import type { TodayPlanFeedback } from "./today-plan-feedback";
// May contain unused imports in some cases
// @ts-ignore
import type { TodayPlanStatusEnum } from "./today-plan-status-enum";

export interface TodayPlan {
  id: number;
  date: string;
  status: TodayPlanStatusEnum;
  generated_at: string;
  check_in: EnergyCheckIn;
  suggestions: Array<PlanItem>;
  feedback: TodayPlanFeedback | null;
  created_at: string;
  updated_at: string;
}
