/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `task_due` - Task Due * `task_overdue` - Task Overdue * `comment` - New Comment * `system` - System
 */

export const TypeEnum = {
  TaskDue: "task_due",
  TaskOverdue: "task_overdue",
  Comment: "comment",
  System: "system",
} as const;

export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
