/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ProductivityPriorityDistribution } from "./productivity-priority-distribution";
// May contain unused imports in some cases
// @ts-ignore
import type { ProductivityStreak } from "./productivity-streak";
// May contain unused imports in some cases
// @ts-ignore
import type { ProductivitySummary } from "./productivity-summary";
// May contain unused imports in some cases
// @ts-ignore
import type { ProductivityWeeklyTrend } from "./productivity-weekly-trend";

export interface UserProductivity {
  summary: ProductivitySummary;
  weekly_trends: Array<ProductivityWeeklyTrend>;
  priority_distribution: Array<ProductivityPriorityDistribution>;
  streak: ProductivityStreak;
}
