/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ProjectRequest } from "./project-request";

export interface UserRequest {
  is_faculty: boolean;
  is_student: boolean;
  is_onboarded: boolean;
  projects: Array<ProjectRequest>;
  theme: string;
  email_digest_enabled: boolean;
}
