/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `list` - List View * `board` - Board View
 */

export const ViewEnum = {
  List: "list",
  Board: "board",
} as const;

export type ViewEnum = (typeof ViewEnum)[keyof typeof ViewEnum];
