/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { Comment } from "../models";
// @ts-ignore
import type { CommentRequest } from "../models";
// @ts-ignore
import type { PaginatedCommentList } from "../models";
// @ts-ignore
import type { PatchedCommentRequest } from "../models";
/**
 * CommentsApi - axios parameter creator
 */
export const CommentsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {CommentRequest} commentRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsCreate: async (
      commentRequest: CommentRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'commentRequest' is not null or undefined
      assertParamExists("commentsCreate", "commentRequest", commentRequest);
      const localVarPath = `/api/comments/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        commentRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this comment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsDestroy: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("commentsDestroy", "id", id);
      const localVarPath = `/api/comments/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {string} [task]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsList: async (
      page?: number,
      task?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/comments/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      if (task !== undefined) {
        localVarQueryParameter["task"] = task;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this comment.
     * @param {PatchedCommentRequest} [patchedCommentRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsPartialUpdate: async (
      id: number,
      patchedCommentRequest?: PatchedCommentRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("commentsPartialUpdate", "id", id);
      const localVarPath = `/api/comments/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        patchedCommentRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this comment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsRetrieve: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("commentsRetrieve", "id", id);
      const localVarPath = `/api/comments/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this comment.
     * @param {CommentRequest} commentRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsUpdate: async (
      id: number,
      commentRequest: CommentRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("commentsUpdate", "id", id);
      // verify required parameter 'commentRequest' is not null or undefined
      assertParamExists("commentsUpdate", "commentRequest", commentRequest);
      const localVarPath = `/api/comments/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        commentRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CommentsApi - functional programming interface
 */
export const CommentsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = CommentsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {CommentRequest} commentRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async commentsCreate(
      commentRequest: CommentRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Comment>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.commentsCreate(
        commentRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CommentsApi.commentsCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this comment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async commentsDestroy(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.commentsDestroy(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CommentsApi.commentsDestroy"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {string} [task]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async commentsList(
      page?: number,
      task?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PaginatedCommentList>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.commentsList(
        page,
        task,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CommentsApi.commentsList"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this comment.
     * @param {PatchedCommentRequest} [patchedCommentRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async commentsPartialUpdate(
      id: number,
      patchedCommentRequest?: PatchedCommentRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Comment>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.commentsPartialUpdate(
          id,
          patchedCommentRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CommentsApi.commentsPartialUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this comment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async commentsRetrieve(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Comment>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.commentsRetrieve(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CommentsApi.commentsRetrieve"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this comment.
     * @param {CommentRequest} commentRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async commentsUpdate(
      id: number,
      commentRequest: CommentRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Comment>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.commentsUpdate(
        id,
        commentRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CommentsApi.commentsUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * CommentsApi - factory interface
 */
export const CommentsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = CommentsApiFp(configuration);
  return {
    /**
     *
     * @param {CommentsApiCommentsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsCreate(
      requestParameters: CommentsApiCommentsCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Comment> {
      return localVarFp
        .commentsCreate(requestParameters.commentRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {CommentsApiCommentsDestroyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsDestroy(
      requestParameters: CommentsApiCommentsDestroyRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .commentsDestroy(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {CommentsApiCommentsListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsList(
      requestParameters: CommentsApiCommentsListRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedCommentList> {
      return localVarFp
        .commentsList(requestParameters.page, requestParameters.task, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {CommentsApiCommentsPartialUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsPartialUpdate(
      requestParameters: CommentsApiCommentsPartialUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Comment> {
      return localVarFp
        .commentsPartialUpdate(
          requestParameters.id,
          requestParameters.patchedCommentRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {CommentsApiCommentsRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsRetrieve(
      requestParameters: CommentsApiCommentsRetrieveRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Comment> {
      return localVarFp
        .commentsRetrieve(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {CommentsApiCommentsUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    commentsUpdate(
      requestParameters: CommentsApiCommentsUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Comment> {
      return localVarFp
        .commentsUpdate(
          requestParameters.id,
          requestParameters.commentRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CommentsApi - interface
 */
export interface CommentsApiInterface {
  /**
   *
   * @param {CommentsApiCommentsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  commentsCreate(
    requestParameters: CommentsApiCommentsCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Comment>;

  /**
   *
   * @param {CommentsApiCommentsDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  commentsDestroy(
    requestParameters: CommentsApiCommentsDestroyRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<void>;

  /**
   *
   * @param {CommentsApiCommentsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  commentsList(
    requestParameters?: CommentsApiCommentsListRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PaginatedCommentList>;

  /**
   *
   * @param {CommentsApiCommentsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  commentsPartialUpdate(
    requestParameters: CommentsApiCommentsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Comment>;

  /**
   *
   * @param {CommentsApiCommentsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  commentsRetrieve(
    requestParameters: CommentsApiCommentsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Comment>;

  /**
   *
   * @param {CommentsApiCommentsUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  commentsUpdate(
    requestParameters: CommentsApiCommentsUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Comment>;
}

/**
 * Request parameters for commentsCreate operation in CommentsApi.
 */
export interface CommentsApiCommentsCreateRequest {
  readonly commentRequest: CommentRequest;
}

/**
 * Request parameters for commentsDestroy operation in CommentsApi.
 */
export interface CommentsApiCommentsDestroyRequest {
  /**
   * A unique integer value identifying this comment.
   */
  readonly id: number;
}

/**
 * Request parameters for commentsList operation in CommentsApi.
 */
export interface CommentsApiCommentsListRequest {
  /**
   * A page number within the paginated result set.
   */
  readonly page?: number;

  readonly task?: string;
}

/**
 * Request parameters for commentsPartialUpdate operation in CommentsApi.
 */
export interface CommentsApiCommentsPartialUpdateRequest {
  /**
   * A unique integer value identifying this comment.
   */
  readonly id: number;

  readonly patchedCommentRequest?: PatchedCommentRequest;
}

/**
 * Request parameters for commentsRetrieve operation in CommentsApi.
 */
export interface CommentsApiCommentsRetrieveRequest {
  /**
   * A unique integer value identifying this comment.
   */
  readonly id: number;
}

/**
 * Request parameters for commentsUpdate operation in CommentsApi.
 */
export interface CommentsApiCommentsUpdateRequest {
  /**
   * A unique integer value identifying this comment.
   */
  readonly id: number;

  readonly commentRequest: CommentRequest;
}

/**
 * CommentsApi - object-oriented interface
 */
export class CommentsApi extends BaseAPI implements CommentsApiInterface {
  /**
   *
   * @param {CommentsApiCommentsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public commentsCreate(
    requestParameters: CommentsApiCommentsCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CommentsApiFp(this.configuration)
      .commentsCreate(requestParameters.commentRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {CommentsApiCommentsDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public commentsDestroy(
    requestParameters: CommentsApiCommentsDestroyRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CommentsApiFp(this.configuration)
      .commentsDestroy(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {CommentsApiCommentsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public commentsList(
    requestParameters: CommentsApiCommentsListRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return CommentsApiFp(this.configuration)
      .commentsList(requestParameters.page, requestParameters.task, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {CommentsApiCommentsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public commentsPartialUpdate(
    requestParameters: CommentsApiCommentsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CommentsApiFp(this.configuration)
      .commentsPartialUpdate(
        requestParameters.id,
        requestParameters.patchedCommentRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {CommentsApiCommentsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public commentsRetrieve(
    requestParameters: CommentsApiCommentsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CommentsApiFp(this.configuration)
      .commentsRetrieve(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {CommentsApiCommentsUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public commentsUpdate(
    requestParameters: CommentsApiCommentsUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return CommentsApiFp(this.configuration)
      .commentsUpdate(
        requestParameters.id,
        requestParameters.commentRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
