/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
/**
 * EmailApi - axios parameter creator
 */
export const EmailApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Send daily digest emails and in-app notifications to all users.  Triggered by Cloud Scheduler. Creates task_due / task_overdue notifications and sends digest emails.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    emailDailyDigestCreate: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/email/daily-digest`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * EmailApi - functional programming interface
 */
export const EmailApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = EmailApiAxiosParamCreator(configuration);
  return {
    /**
     * Send daily digest emails and in-app notifications to all users.  Triggered by Cloud Scheduler. Creates task_due / task_overdue notifications and sends digest emails.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async emailDailyDigestCreate(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.emailDailyDigestCreate(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["EmailApi.emailDailyDigestCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * EmailApi - factory interface
 */
export const EmailApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = EmailApiFp(configuration);
  return {
    /**
     * Send daily digest emails and in-app notifications to all users.  Triggered by Cloud Scheduler. Creates task_due / task_overdue notifications and sends digest emails.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    emailDailyDigestCreate(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .emailDailyDigestCreate(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * EmailApi - interface
 */
export interface EmailApiInterface {
  /**
   * Send daily digest emails and in-app notifications to all users.  Triggered by Cloud Scheduler. Creates task_due / task_overdue notifications and sends digest emails.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  emailDailyDigestCreate(options?: RawAxiosRequestConfig): AxiosPromise<void>;
}

/**
 * EmailApi - object-oriented interface
 */
export class EmailApi extends BaseAPI implements EmailApiInterface {
  /**
   * Send daily digest emails and in-app notifications to all users.  Triggered by Cloud Scheduler. Creates task_due / task_overdue notifications and sends digest emails.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public emailDailyDigestCreate(options?: RawAxiosRequestConfig) {
    return EmailApiFp(this.configuration)
      .emailDailyDigestCreate(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
