/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { Notification } from "../models";
// @ts-ignore
import type { NotificationRequest } from "../models";
// @ts-ignore
import type { PaginatedNotificationList } from "../models";
// @ts-ignore
import type { PatchedNotificationRequest } from "../models";
/**
 * NotificationsApi - axios parameter creator
 */
export const NotificationsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {NotificationRequest} [notificationRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsCreate: async (
      notificationRequest?: NotificationRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/notifications/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        notificationRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsList: async (
      page?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/notifications/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this notification.
     * @param {PatchedNotificationRequest} [patchedNotificationRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsPartialUpdate: async (
      id: number,
      patchedNotificationRequest?: PatchedNotificationRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("notificationsPartialUpdate", "id", id);
      const localVarPath = `/api/notifications/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        patchedNotificationRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {NotificationRequest} [notificationRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsReadAllCreate: async (
      notificationRequest?: NotificationRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/notifications/read_all/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        notificationRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this notification.
     * @param {NotificationRequest} [notificationRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsReadCreate: async (
      id: number,
      notificationRequest?: NotificationRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("notificationsReadCreate", "id", id);
      const localVarPath = `/api/notifications/{id}/read/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        notificationRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this notification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsRetrieve: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("notificationsRetrieve", "id", id);
      const localVarPath = `/api/notifications/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsUnreadCountRetrieve: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/notifications/unread_count/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * NotificationsApi - functional programming interface
 */
export const NotificationsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    NotificationsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {NotificationRequest} [notificationRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async notificationsCreate(
      notificationRequest?: NotificationRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.notificationsCreate(
          notificationRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["NotificationsApi.notificationsCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async notificationsList(
      page?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PaginatedNotificationList>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.notificationsList(page, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["NotificationsApi.notificationsList"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this notification.
     * @param {PatchedNotificationRequest} [patchedNotificationRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async notificationsPartialUpdate(
      id: number,
      patchedNotificationRequest?: PatchedNotificationRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.notificationsPartialUpdate(
          id,
          patchedNotificationRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["NotificationsApi.notificationsPartialUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {NotificationRequest} [notificationRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async notificationsReadAllCreate(
      notificationRequest?: NotificationRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.notificationsReadAllCreate(
          notificationRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["NotificationsApi.notificationsReadAllCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this notification.
     * @param {NotificationRequest} [notificationRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async notificationsReadCreate(
      id: number,
      notificationRequest?: NotificationRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.notificationsReadCreate(
          id,
          notificationRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["NotificationsApi.notificationsReadCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this notification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async notificationsRetrieve(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.notificationsRetrieve(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["NotificationsApi.notificationsRetrieve"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async notificationsUnreadCountRetrieve(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.notificationsUnreadCountRetrieve(
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "NotificationsApi.notificationsUnreadCountRetrieve"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * NotificationsApi - factory interface
 */
export const NotificationsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = NotificationsApiFp(configuration);
  return {
    /**
     *
     * @param {NotificationsApiNotificationsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsCreate(
      requestParameters: NotificationsApiNotificationsCreateRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .notificationsCreate(requestParameters.notificationRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {NotificationsApiNotificationsListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsList(
      requestParameters: NotificationsApiNotificationsListRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedNotificationList> {
      return localVarFp
        .notificationsList(requestParameters.page, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {NotificationsApiNotificationsPartialUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsPartialUpdate(
      requestParameters: NotificationsApiNotificationsPartialUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .notificationsPartialUpdate(
          requestParameters.id,
          requestParameters.patchedNotificationRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {NotificationsApiNotificationsReadAllCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsReadAllCreate(
      requestParameters: NotificationsApiNotificationsReadAllCreateRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .notificationsReadAllCreate(
          requestParameters.notificationRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {NotificationsApiNotificationsReadCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsReadCreate(
      requestParameters: NotificationsApiNotificationsReadCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .notificationsReadCreate(
          requestParameters.id,
          requestParameters.notificationRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {NotificationsApiNotificationsRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsRetrieve(
      requestParameters: NotificationsApiNotificationsRetrieveRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .notificationsRetrieve(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsUnreadCountRetrieve(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .notificationsUnreadCountRetrieve(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * NotificationsApi - interface
 */
export interface NotificationsApiInterface {
  /**
   *
   * @param {NotificationsApiNotificationsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  notificationsCreate(
    requestParameters?: NotificationsApiNotificationsCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Notification>;

  /**
   *
   * @param {NotificationsApiNotificationsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  notificationsList(
    requestParameters?: NotificationsApiNotificationsListRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PaginatedNotificationList>;

  /**
   *
   * @param {NotificationsApiNotificationsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  notificationsPartialUpdate(
    requestParameters: NotificationsApiNotificationsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Notification>;

  /**
   *
   * @param {NotificationsApiNotificationsReadAllCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  notificationsReadAllCreate(
    requestParameters?: NotificationsApiNotificationsReadAllCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Notification>;

  /**
   *
   * @param {NotificationsApiNotificationsReadCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  notificationsReadCreate(
    requestParameters: NotificationsApiNotificationsReadCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Notification>;

  /**
   *
   * @param {NotificationsApiNotificationsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  notificationsRetrieve(
    requestParameters: NotificationsApiNotificationsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Notification>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  notificationsUnreadCountRetrieve(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Notification>;
}

/**
 * Request parameters for notificationsCreate operation in NotificationsApi.
 */
export interface NotificationsApiNotificationsCreateRequest {
  readonly notificationRequest?: NotificationRequest;
}

/**
 * Request parameters for notificationsList operation in NotificationsApi.
 */
export interface NotificationsApiNotificationsListRequest {
  /**
   * A page number within the paginated result set.
   */
  readonly page?: number;
}

/**
 * Request parameters for notificationsPartialUpdate operation in NotificationsApi.
 */
export interface NotificationsApiNotificationsPartialUpdateRequest {
  /**
   * A unique integer value identifying this notification.
   */
  readonly id: number;

  readonly patchedNotificationRequest?: PatchedNotificationRequest;
}

/**
 * Request parameters for notificationsReadAllCreate operation in NotificationsApi.
 */
export interface NotificationsApiNotificationsReadAllCreateRequest {
  readonly notificationRequest?: NotificationRequest;
}

/**
 * Request parameters for notificationsReadCreate operation in NotificationsApi.
 */
export interface NotificationsApiNotificationsReadCreateRequest {
  /**
   * A unique integer value identifying this notification.
   */
  readonly id: number;

  readonly notificationRequest?: NotificationRequest;
}

/**
 * Request parameters for notificationsRetrieve operation in NotificationsApi.
 */
export interface NotificationsApiNotificationsRetrieveRequest {
  /**
   * A unique integer value identifying this notification.
   */
  readonly id: number;
}

/**
 * NotificationsApi - object-oriented interface
 */
export class NotificationsApi
  extends BaseAPI
  implements NotificationsApiInterface
{
  /**
   *
   * @param {NotificationsApiNotificationsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public notificationsCreate(
    requestParameters: NotificationsApiNotificationsCreateRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return NotificationsApiFp(this.configuration)
      .notificationsCreate(requestParameters.notificationRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {NotificationsApiNotificationsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public notificationsList(
    requestParameters: NotificationsApiNotificationsListRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return NotificationsApiFp(this.configuration)
      .notificationsList(requestParameters.page, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {NotificationsApiNotificationsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public notificationsPartialUpdate(
    requestParameters: NotificationsApiNotificationsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return NotificationsApiFp(this.configuration)
      .notificationsPartialUpdate(
        requestParameters.id,
        requestParameters.patchedNotificationRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {NotificationsApiNotificationsReadAllCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public notificationsReadAllCreate(
    requestParameters: NotificationsApiNotificationsReadAllCreateRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return NotificationsApiFp(this.configuration)
      .notificationsReadAllCreate(
        requestParameters.notificationRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {NotificationsApiNotificationsReadCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public notificationsReadCreate(
    requestParameters: NotificationsApiNotificationsReadCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return NotificationsApiFp(this.configuration)
      .notificationsReadCreate(
        requestParameters.id,
        requestParameters.notificationRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {NotificationsApiNotificationsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public notificationsRetrieve(
    requestParameters: NotificationsApiNotificationsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return NotificationsApiFp(this.configuration)
      .notificationsRetrieve(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public notificationsUnreadCountRetrieve(options?: RawAxiosRequestConfig) {
    return NotificationsApiFp(this.configuration)
      .notificationsUnreadCountRetrieve(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
