/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { EnergyCheckInRequest } from "../models";
// @ts-ignore
import type { PlanItem } from "../models";
// @ts-ignore
import type { PlannerEvaluationSummary } from "../models";
// @ts-ignore
import type { SnoozePlanItemRequest } from "../models";
// @ts-ignore
import type { TodayPlan } from "../models";
// @ts-ignore
import type { TodayPlanFeedback } from "../models";
// @ts-ignore
import type { TodayPlanFeedbackRequest } from "../models";
/**
 * PlannerApi - axios parameter creator
 */
export const PlannerApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {EnergyCheckInRequest} [energyCheckInRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerCheckInCreate: async (
      energyCheckInRequest?: EnergyCheckInRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/planner/check-in/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        energyCheckInRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerEvaluationRetrieve: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/planner/evaluation/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {TodayPlanFeedbackRequest} todayPlanFeedbackRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerFeedbackCreate: async (
      todayPlanFeedbackRequest: TodayPlanFeedbackRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'todayPlanFeedbackRequest' is not null or undefined
      assertParamExists(
        "plannerFeedbackCreate",
        "todayPlanFeedbackRequest",
        todayPlanFeedbackRequest,
      );
      const localVarPath = `/api/planner/feedback/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        todayPlanFeedbackRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerRebuildCreate: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/planner/rebuild/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} itemId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerSuggestionsAcceptCreate: async (
      itemId: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'itemId' is not null or undefined
      assertParamExists("plannerSuggestionsAcceptCreate", "itemId", itemId);
      const localVarPath = `/api/planner/suggestions/{item_id}/accept/`.replace(
        `{${"item_id"}}`,
        encodeURIComponent(String(itemId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} itemId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerSuggestionsDismissCreate: async (
      itemId: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'itemId' is not null or undefined
      assertParamExists("plannerSuggestionsDismissCreate", "itemId", itemId);
      const localVarPath =
        `/api/planner/suggestions/{item_id}/dismiss/`.replace(
          `{${"item_id"}}`,
          encodeURIComponent(String(itemId)),
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} itemId
     * @param {SnoozePlanItemRequest} [snoozePlanItemRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerSuggestionsSnoozeCreate: async (
      itemId: number,
      snoozePlanItemRequest?: SnoozePlanItemRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'itemId' is not null or undefined
      assertParamExists("plannerSuggestionsSnoozeCreate", "itemId", itemId);
      const localVarPath = `/api/planner/suggestions/{item_id}/snooze/`.replace(
        `{${"item_id"}}`,
        encodeURIComponent(String(itemId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        snoozePlanItemRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerTodayRetrieve: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/planner/today/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PlannerApi - functional programming interface
 */
export const PlannerApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PlannerApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {EnergyCheckInRequest} [energyCheckInRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async plannerCheckInCreate(
      energyCheckInRequest?: EnergyCheckInRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TodayPlan>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.plannerCheckInCreate(
          energyCheckInRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PlannerApi.plannerCheckInCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async plannerEvaluationRetrieve(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PlannerEvaluationSummary>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.plannerEvaluationRetrieve(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PlannerApi.plannerEvaluationRetrieve"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {TodayPlanFeedbackRequest} todayPlanFeedbackRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async plannerFeedbackCreate(
      todayPlanFeedbackRequest: TodayPlanFeedbackRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TodayPlanFeedback>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.plannerFeedbackCreate(
          todayPlanFeedbackRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PlannerApi.plannerFeedbackCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async plannerRebuildCreate(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TodayPlan>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.plannerRebuildCreate(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PlannerApi.plannerRebuildCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} itemId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async plannerSuggestionsAcceptCreate(
      itemId: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlanItem>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.plannerSuggestionsAcceptCreate(
          itemId,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PlannerApi.plannerSuggestionsAcceptCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} itemId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async plannerSuggestionsDismissCreate(
      itemId: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlanItem>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.plannerSuggestionsDismissCreate(
          itemId,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PlannerApi.plannerSuggestionsDismissCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} itemId
     * @param {SnoozePlanItemRequest} [snoozePlanItemRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async plannerSuggestionsSnoozeCreate(
      itemId: number,
      snoozePlanItemRequest?: SnoozePlanItemRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlanItem>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.plannerSuggestionsSnoozeCreate(
          itemId,
          snoozePlanItemRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PlannerApi.plannerSuggestionsSnoozeCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async plannerTodayRetrieve(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TodayPlan>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.plannerTodayRetrieve(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["PlannerApi.plannerTodayRetrieve"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * PlannerApi - factory interface
 */
export const PlannerApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PlannerApiFp(configuration);
  return {
    /**
     *
     * @param {PlannerApiPlannerCheckInCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerCheckInCreate(
      requestParameters: PlannerApiPlannerCheckInCreateRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TodayPlan> {
      return localVarFp
        .plannerCheckInCreate(requestParameters.energyCheckInRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerEvaluationRetrieve(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PlannerEvaluationSummary> {
      return localVarFp
        .plannerEvaluationRetrieve(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {PlannerApiPlannerFeedbackCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerFeedbackCreate(
      requestParameters: PlannerApiPlannerFeedbackCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TodayPlanFeedback> {
      return localVarFp
        .plannerFeedbackCreate(
          requestParameters.todayPlanFeedbackRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerRebuildCreate(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TodayPlan> {
      return localVarFp
        .plannerRebuildCreate(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {PlannerApiPlannerSuggestionsAcceptCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerSuggestionsAcceptCreate(
      requestParameters: PlannerApiPlannerSuggestionsAcceptCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PlanItem> {
      return localVarFp
        .plannerSuggestionsAcceptCreate(requestParameters.itemId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {PlannerApiPlannerSuggestionsDismissCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerSuggestionsDismissCreate(
      requestParameters: PlannerApiPlannerSuggestionsDismissCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PlanItem> {
      return localVarFp
        .plannerSuggestionsDismissCreate(requestParameters.itemId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {PlannerApiPlannerSuggestionsSnoozeCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerSuggestionsSnoozeCreate(
      requestParameters: PlannerApiPlannerSuggestionsSnoozeCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PlanItem> {
      return localVarFp
        .plannerSuggestionsSnoozeCreate(
          requestParameters.itemId,
          requestParameters.snoozePlanItemRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    plannerTodayRetrieve(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TodayPlan> {
      return localVarFp
        .plannerTodayRetrieve(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PlannerApi - interface
 */
export interface PlannerApiInterface {
  /**
   *
   * @param {PlannerApiPlannerCheckInCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  plannerCheckInCreate(
    requestParameters?: PlannerApiPlannerCheckInCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<TodayPlan>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  plannerEvaluationRetrieve(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PlannerEvaluationSummary>;

  /**
   *
   * @param {PlannerApiPlannerFeedbackCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  plannerFeedbackCreate(
    requestParameters: PlannerApiPlannerFeedbackCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<TodayPlanFeedback>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  plannerRebuildCreate(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<TodayPlan>;

  /**
   *
   * @param {PlannerApiPlannerSuggestionsAcceptCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  plannerSuggestionsAcceptCreate(
    requestParameters: PlannerApiPlannerSuggestionsAcceptCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PlanItem>;

  /**
   *
   * @param {PlannerApiPlannerSuggestionsDismissCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  plannerSuggestionsDismissCreate(
    requestParameters: PlannerApiPlannerSuggestionsDismissCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PlanItem>;

  /**
   *
   * @param {PlannerApiPlannerSuggestionsSnoozeCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  plannerSuggestionsSnoozeCreate(
    requestParameters: PlannerApiPlannerSuggestionsSnoozeCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PlanItem>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  plannerTodayRetrieve(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<TodayPlan>;
}

/**
 * Request parameters for plannerCheckInCreate operation in PlannerApi.
 */
export interface PlannerApiPlannerCheckInCreateRequest {
  readonly energyCheckInRequest?: EnergyCheckInRequest;
}

/**
 * Request parameters for plannerFeedbackCreate operation in PlannerApi.
 */
export interface PlannerApiPlannerFeedbackCreateRequest {
  readonly todayPlanFeedbackRequest: TodayPlanFeedbackRequest;
}

/**
 * Request parameters for plannerSuggestionsAcceptCreate operation in PlannerApi.
 */
export interface PlannerApiPlannerSuggestionsAcceptCreateRequest {
  readonly itemId: number;
}

/**
 * Request parameters for plannerSuggestionsDismissCreate operation in PlannerApi.
 */
export interface PlannerApiPlannerSuggestionsDismissCreateRequest {
  readonly itemId: number;
}

/**
 * Request parameters for plannerSuggestionsSnoozeCreate operation in PlannerApi.
 */
export interface PlannerApiPlannerSuggestionsSnoozeCreateRequest {
  readonly itemId: number;

  readonly snoozePlanItemRequest?: SnoozePlanItemRequest;
}

/**
 * PlannerApi - object-oriented interface
 */
export class PlannerApi extends BaseAPI implements PlannerApiInterface {
  /**
   *
   * @param {PlannerApiPlannerCheckInCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public plannerCheckInCreate(
    requestParameters: PlannerApiPlannerCheckInCreateRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return PlannerApiFp(this.configuration)
      .plannerCheckInCreate(requestParameters.energyCheckInRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public plannerEvaluationRetrieve(options?: RawAxiosRequestConfig) {
    return PlannerApiFp(this.configuration)
      .plannerEvaluationRetrieve(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {PlannerApiPlannerFeedbackCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public plannerFeedbackCreate(
    requestParameters: PlannerApiPlannerFeedbackCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PlannerApiFp(this.configuration)
      .plannerFeedbackCreate(
        requestParameters.todayPlanFeedbackRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public plannerRebuildCreate(options?: RawAxiosRequestConfig) {
    return PlannerApiFp(this.configuration)
      .plannerRebuildCreate(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {PlannerApiPlannerSuggestionsAcceptCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public plannerSuggestionsAcceptCreate(
    requestParameters: PlannerApiPlannerSuggestionsAcceptCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PlannerApiFp(this.configuration)
      .plannerSuggestionsAcceptCreate(requestParameters.itemId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {PlannerApiPlannerSuggestionsDismissCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public plannerSuggestionsDismissCreate(
    requestParameters: PlannerApiPlannerSuggestionsDismissCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PlannerApiFp(this.configuration)
      .plannerSuggestionsDismissCreate(requestParameters.itemId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {PlannerApiPlannerSuggestionsSnoozeCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public plannerSuggestionsSnoozeCreate(
    requestParameters: PlannerApiPlannerSuggestionsSnoozeCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return PlannerApiFp(this.configuration)
      .plannerSuggestionsSnoozeCreate(
        requestParameters.itemId,
        requestParameters.snoozePlanItemRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public plannerTodayRetrieve(options?: RawAxiosRequestConfig) {
    return PlannerApiFp(this.configuration)
      .plannerTodayRetrieve(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
