/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Task management API for UPOU students and faculty
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { PaginatedProjectSectionList } from "../models";
// @ts-ignore
import type { PatchedProjectSectionRequest } from "../models";
// @ts-ignore
import type { ProjectSection } from "../models";
// @ts-ignore
import type { ProjectSectionRequest } from "../models";
/**
 * ProjectSectionsApi - axios parameter creator
 */
export const ProjectSectionsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {ProjectSectionRequest} projectSectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsBulkUpdateUpdate: async (
      projectSectionRequest: ProjectSectionRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectSectionRequest' is not null or undefined
      assertParamExists(
        "projectSectionsBulkUpdateUpdate",
        "projectSectionRequest",
        projectSectionRequest,
      );
      const localVarPath = `/api/project_sections/bulk_update/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        projectSectionRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ProjectSectionRequest} projectSectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsCreate: async (
      projectSectionRequest: ProjectSectionRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectSectionRequest' is not null or undefined
      assertParamExists(
        "projectSectionsCreate",
        "projectSectionRequest",
        projectSectionRequest,
      );
      const localVarPath = `/api/project_sections/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        projectSectionRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsDestroy: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("projectSectionsDestroy", "id", id);
      const localVarPath = `/api/project_sections/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {ProjectSectionRequest} projectSectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsDuplicateCreate: async (
      id: number,
      projectSectionRequest: ProjectSectionRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("projectSectionsDuplicateCreate", "id", id);
      // verify required parameter 'projectSectionRequest' is not null or undefined
      assertParamExists(
        "projectSectionsDuplicateCreate",
        "projectSectionRequest",
        projectSectionRequest,
      );
      const localVarPath = `/api/project_sections/{id}/duplicate/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        projectSectionRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsList: async (
      page?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/project_sections/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {PatchedProjectSectionRequest} [patchedProjectSectionRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsPartialUpdate: async (
      id: number,
      patchedProjectSectionRequest?: PatchedProjectSectionRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("projectSectionsPartialUpdate", "id", id);
      const localVarPath = `/api/project_sections/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        patchedProjectSectionRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsRetrieve: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("projectSectionsRetrieve", "id", id);
      const localVarPath = `/api/project_sections/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {ProjectSectionRequest} projectSectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsUpdate: async (
      id: number,
      projectSectionRequest: ProjectSectionRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("projectSectionsUpdate", "id", id);
      // verify required parameter 'projectSectionRequest' is not null or undefined
      assertParamExists(
        "projectSectionsUpdate",
        "projectSectionRequest",
        projectSectionRequest,
      );
      const localVarPath = `/api/project_sections/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        projectSectionRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ProjectSectionsApi - functional programming interface
 */
export const ProjectSectionsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    ProjectSectionsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {ProjectSectionRequest} projectSectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectSectionsBulkUpdateUpdate(
      projectSectionRequest: ProjectSectionRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectSection>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectSectionsBulkUpdateUpdate(
          projectSectionRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "ProjectSectionsApi.projectSectionsBulkUpdateUpdate"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ProjectSectionRequest} projectSectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectSectionsCreate(
      projectSectionRequest: ProjectSectionRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectSection>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectSectionsCreate(
          projectSectionRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectSectionsApi.projectSectionsCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectSectionsDestroy(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectSectionsDestroy(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectSectionsApi.projectSectionsDestroy"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {ProjectSectionRequest} projectSectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectSectionsDuplicateCreate(
      id: number,
      projectSectionRequest: ProjectSectionRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectSection>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectSectionsDuplicateCreate(
          id,
          projectSectionRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "ProjectSectionsApi.projectSectionsDuplicateCreate"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectSectionsList(
      page?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PaginatedProjectSectionList>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectSectionsList(page, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectSectionsApi.projectSectionsList"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {PatchedProjectSectionRequest} [patchedProjectSectionRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectSectionsPartialUpdate(
      id: number,
      patchedProjectSectionRequest?: PatchedProjectSectionRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectSection>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectSectionsPartialUpdate(
          id,
          patchedProjectSectionRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectSectionsApi.projectSectionsPartialUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectSectionsRetrieve(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectSection>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectSectionsRetrieve(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectSectionsApi.projectSectionsRetrieve"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project section.
     * @param {ProjectSectionRequest} projectSectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectSectionsUpdate(
      id: number,
      projectSectionRequest: ProjectSectionRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectSection>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectSectionsUpdate(
          id,
          projectSectionRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectSectionsApi.projectSectionsUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ProjectSectionsApi - factory interface
 */
export const ProjectSectionsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ProjectSectionsApiFp(configuration);
  return {
    /**
     *
     * @param {ProjectSectionsApiProjectSectionsBulkUpdateUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsBulkUpdateUpdate(
      requestParameters: ProjectSectionsApiProjectSectionsBulkUpdateUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectSection> {
      return localVarFp
        .projectSectionsBulkUpdateUpdate(
          requestParameters.projectSectionRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectSectionsApiProjectSectionsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsCreate(
      requestParameters: ProjectSectionsApiProjectSectionsCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectSection> {
      return localVarFp
        .projectSectionsCreate(requestParameters.projectSectionRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectSectionsApiProjectSectionsDestroyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsDestroy(
      requestParameters: ProjectSectionsApiProjectSectionsDestroyRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .projectSectionsDestroy(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectSectionsApiProjectSectionsDuplicateCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsDuplicateCreate(
      requestParameters: ProjectSectionsApiProjectSectionsDuplicateCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectSection> {
      return localVarFp
        .projectSectionsDuplicateCreate(
          requestParameters.id,
          requestParameters.projectSectionRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectSectionsApiProjectSectionsListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsList(
      requestParameters: ProjectSectionsApiProjectSectionsListRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedProjectSectionList> {
      return localVarFp
        .projectSectionsList(requestParameters.page, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectSectionsApiProjectSectionsPartialUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsPartialUpdate(
      requestParameters: ProjectSectionsApiProjectSectionsPartialUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectSection> {
      return localVarFp
        .projectSectionsPartialUpdate(
          requestParameters.id,
          requestParameters.patchedProjectSectionRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectSectionsApiProjectSectionsRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsRetrieve(
      requestParameters: ProjectSectionsApiProjectSectionsRetrieveRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectSection> {
      return localVarFp
        .projectSectionsRetrieve(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectSectionsApiProjectSectionsUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectSectionsUpdate(
      requestParameters: ProjectSectionsApiProjectSectionsUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectSection> {
      return localVarFp
        .projectSectionsUpdate(
          requestParameters.id,
          requestParameters.projectSectionRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ProjectSectionsApi - interface
 */
export interface ProjectSectionsApiInterface {
  /**
   *
   * @param {ProjectSectionsApiProjectSectionsBulkUpdateUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectSectionsBulkUpdateUpdate(
    requestParameters: ProjectSectionsApiProjectSectionsBulkUpdateUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectSection>;

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectSectionsCreate(
    requestParameters: ProjectSectionsApiProjectSectionsCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectSection>;

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectSectionsDestroy(
    requestParameters: ProjectSectionsApiProjectSectionsDestroyRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<void>;

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsDuplicateCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectSectionsDuplicateCreate(
    requestParameters: ProjectSectionsApiProjectSectionsDuplicateCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectSection>;

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectSectionsList(
    requestParameters?: ProjectSectionsApiProjectSectionsListRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PaginatedProjectSectionList>;

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectSectionsPartialUpdate(
    requestParameters: ProjectSectionsApiProjectSectionsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectSection>;

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectSectionsRetrieve(
    requestParameters: ProjectSectionsApiProjectSectionsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectSection>;

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectSectionsUpdate(
    requestParameters: ProjectSectionsApiProjectSectionsUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectSection>;
}

/**
 * Request parameters for projectSectionsBulkUpdateUpdate operation in ProjectSectionsApi.
 */
export interface ProjectSectionsApiProjectSectionsBulkUpdateUpdateRequest {
  readonly projectSectionRequest: ProjectSectionRequest;
}

/**
 * Request parameters for projectSectionsCreate operation in ProjectSectionsApi.
 */
export interface ProjectSectionsApiProjectSectionsCreateRequest {
  readonly projectSectionRequest: ProjectSectionRequest;
}

/**
 * Request parameters for projectSectionsDestroy operation in ProjectSectionsApi.
 */
export interface ProjectSectionsApiProjectSectionsDestroyRequest {
  /**
   * A unique integer value identifying this project section.
   */
  readonly id: number;
}

/**
 * Request parameters for projectSectionsDuplicateCreate operation in ProjectSectionsApi.
 */
export interface ProjectSectionsApiProjectSectionsDuplicateCreateRequest {
  /**
   * A unique integer value identifying this project section.
   */
  readonly id: number;

  readonly projectSectionRequest: ProjectSectionRequest;
}

/**
 * Request parameters for projectSectionsList operation in ProjectSectionsApi.
 */
export interface ProjectSectionsApiProjectSectionsListRequest {
  /**
   * A page number within the paginated result set.
   */
  readonly page?: number;
}

/**
 * Request parameters for projectSectionsPartialUpdate operation in ProjectSectionsApi.
 */
export interface ProjectSectionsApiProjectSectionsPartialUpdateRequest {
  /**
   * A unique integer value identifying this project section.
   */
  readonly id: number;

  readonly patchedProjectSectionRequest?: PatchedProjectSectionRequest;
}

/**
 * Request parameters for projectSectionsRetrieve operation in ProjectSectionsApi.
 */
export interface ProjectSectionsApiProjectSectionsRetrieveRequest {
  /**
   * A unique integer value identifying this project section.
   */
  readonly id: number;
}

/**
 * Request parameters for projectSectionsUpdate operation in ProjectSectionsApi.
 */
export interface ProjectSectionsApiProjectSectionsUpdateRequest {
  /**
   * A unique integer value identifying this project section.
   */
  readonly id: number;

  readonly projectSectionRequest: ProjectSectionRequest;
}

/**
 * ProjectSectionsApi - object-oriented interface
 */
export class ProjectSectionsApi
  extends BaseAPI
  implements ProjectSectionsApiInterface
{
  /**
   *
   * @param {ProjectSectionsApiProjectSectionsBulkUpdateUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectSectionsBulkUpdateUpdate(
    requestParameters: ProjectSectionsApiProjectSectionsBulkUpdateUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectSectionsApiFp(this.configuration)
      .projectSectionsBulkUpdateUpdate(
        requestParameters.projectSectionRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectSectionsCreate(
    requestParameters: ProjectSectionsApiProjectSectionsCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectSectionsApiFp(this.configuration)
      .projectSectionsCreate(requestParameters.projectSectionRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectSectionsDestroy(
    requestParameters: ProjectSectionsApiProjectSectionsDestroyRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectSectionsApiFp(this.configuration)
      .projectSectionsDestroy(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsDuplicateCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectSectionsDuplicateCreate(
    requestParameters: ProjectSectionsApiProjectSectionsDuplicateCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectSectionsApiFp(this.configuration)
      .projectSectionsDuplicateCreate(
        requestParameters.id,
        requestParameters.projectSectionRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectSectionsList(
    requestParameters: ProjectSectionsApiProjectSectionsListRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectSectionsApiFp(this.configuration)
      .projectSectionsList(requestParameters.page, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectSectionsPartialUpdate(
    requestParameters: ProjectSectionsApiProjectSectionsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectSectionsApiFp(this.configuration)
      .projectSectionsPartialUpdate(
        requestParameters.id,
        requestParameters.patchedProjectSectionRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectSectionsRetrieve(
    requestParameters: ProjectSectionsApiProjectSectionsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectSectionsApiFp(this.configuration)
      .projectSectionsRetrieve(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectSectionsApiProjectSectionsUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectSectionsUpdate(
    requestParameters: ProjectSectionsApiProjectSectionsUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectSectionsApiFp(this.configuration)
      .projectSectionsUpdate(
        requestParameters.id,
        requestParameters.projectSectionRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
