/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { PaginatedProjectList } from "../models";
// @ts-ignore
import type { PatchedProjectDetailRequest } from "../models";
// @ts-ignore
import type { ProjectDetail } from "../models";
// @ts-ignore
import type { ProjectDetailRequest } from "../models";
/**
 * ProjectsApi - axios parameter creator
 */
export const ProjectsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {ProjectDetailRequest} projectDetailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsBulkUpdateUpdate: async (
      projectDetailRequest: ProjectDetailRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectDetailRequest' is not null or undefined
      assertParamExists(
        "projectsBulkUpdateUpdate",
        "projectDetailRequest",
        projectDetailRequest,
      );
      const localVarPath = `/api/projects/bulk_update/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        projectDetailRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ProjectDetailRequest} projectDetailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsCreate: async (
      projectDetailRequest: ProjectDetailRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectDetailRequest' is not null or undefined
      assertParamExists(
        "projectsCreate",
        "projectDetailRequest",
        projectDetailRequest,
      );
      const localVarPath = `/api/projects/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        projectDetailRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsDestroy: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("projectsDestroy", "id", id);
      const localVarPath = `/api/projects/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsList: async (
      page?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/projects/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project.
     * @param {PatchedProjectDetailRequest} [patchedProjectDetailRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsPartialUpdate: async (
      id: number,
      patchedProjectDetailRequest?: PatchedProjectDetailRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("projectsPartialUpdate", "id", id);
      const localVarPath = `/api/projects/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        patchedProjectDetailRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsRetrieve: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("projectsRetrieve", "id", id);
      const localVarPath = `/api/projects/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project.
     * @param {ProjectDetailRequest} projectDetailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsUpdate: async (
      id: number,
      projectDetailRequest: ProjectDetailRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("projectsUpdate", "id", id);
      // verify required parameter 'projectDetailRequest' is not null or undefined
      assertParamExists(
        "projectsUpdate",
        "projectDetailRequest",
        projectDetailRequest,
      );
      const localVarPath = `/api/projects/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        projectDetailRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ProjectsApi - functional programming interface
 */
export const ProjectsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ProjectsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {ProjectDetailRequest} projectDetailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectsBulkUpdateUpdate(
      projectDetailRequest: ProjectDetailRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectDetail>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectsBulkUpdateUpdate(
          projectDetailRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectsApi.projectsBulkUpdateUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ProjectDetailRequest} projectDetailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectsCreate(
      projectDetailRequest: ProjectDetailRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectDetail>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.projectsCreate(
        projectDetailRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectsApi.projectsCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectsDestroy(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.projectsDestroy(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectsApi.projectsDestroy"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectsList(
      page?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PaginatedProjectList>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.projectsList(
        page,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectsApi.projectsList"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project.
     * @param {PatchedProjectDetailRequest} [patchedProjectDetailRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectsPartialUpdate(
      id: number,
      patchedProjectDetailRequest?: PatchedProjectDetailRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectDetail>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectsPartialUpdate(
          id,
          patchedProjectDetailRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectsApi.projectsPartialUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectsRetrieve(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectDetail>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.projectsRetrieve(id, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectsApi.projectsRetrieve"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this project.
     * @param {ProjectDetailRequest} projectDetailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async projectsUpdate(
      id: number,
      projectDetailRequest: ProjectDetailRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectDetail>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.projectsUpdate(
        id,
        projectDetailRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["ProjectsApi.projectsUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ProjectsApi - factory interface
 */
export const ProjectsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ProjectsApiFp(configuration);
  return {
    /**
     *
     * @param {ProjectsApiProjectsBulkUpdateUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsBulkUpdateUpdate(
      requestParameters: ProjectsApiProjectsBulkUpdateUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectDetail> {
      return localVarFp
        .projectsBulkUpdateUpdate(
          requestParameters.projectDetailRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectsApiProjectsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsCreate(
      requestParameters: ProjectsApiProjectsCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectDetail> {
      return localVarFp
        .projectsCreate(requestParameters.projectDetailRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectsApiProjectsDestroyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsDestroy(
      requestParameters: ProjectsApiProjectsDestroyRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .projectsDestroy(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectsApiProjectsListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsList(
      requestParameters: ProjectsApiProjectsListRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedProjectList> {
      return localVarFp
        .projectsList(requestParameters.page, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectsApiProjectsPartialUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsPartialUpdate(
      requestParameters: ProjectsApiProjectsPartialUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectDetail> {
      return localVarFp
        .projectsPartialUpdate(
          requestParameters.id,
          requestParameters.patchedProjectDetailRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectsApiProjectsRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsRetrieve(
      requestParameters: ProjectsApiProjectsRetrieveRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectDetail> {
      return localVarFp
        .projectsRetrieve(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {ProjectsApiProjectsUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    projectsUpdate(
      requestParameters: ProjectsApiProjectsUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProjectDetail> {
      return localVarFp
        .projectsUpdate(
          requestParameters.id,
          requestParameters.projectDetailRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ProjectsApi - interface
 */
export interface ProjectsApiInterface {
  /**
   *
   * @param {ProjectsApiProjectsBulkUpdateUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectsBulkUpdateUpdate(
    requestParameters: ProjectsApiProjectsBulkUpdateUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectDetail>;

  /**
   *
   * @param {ProjectsApiProjectsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectsCreate(
    requestParameters: ProjectsApiProjectsCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectDetail>;

  /**
   *
   * @param {ProjectsApiProjectsDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectsDestroy(
    requestParameters: ProjectsApiProjectsDestroyRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<void>;

  /**
   *
   * @param {ProjectsApiProjectsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectsList(
    requestParameters?: ProjectsApiProjectsListRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PaginatedProjectList>;

  /**
   *
   * @param {ProjectsApiProjectsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectsPartialUpdate(
    requestParameters: ProjectsApiProjectsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectDetail>;

  /**
   *
   * @param {ProjectsApiProjectsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectsRetrieve(
    requestParameters: ProjectsApiProjectsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectDetail>;

  /**
   *
   * @param {ProjectsApiProjectsUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  projectsUpdate(
    requestParameters: ProjectsApiProjectsUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ProjectDetail>;
}

/**
 * Request parameters for projectsBulkUpdateUpdate operation in ProjectsApi.
 */
export interface ProjectsApiProjectsBulkUpdateUpdateRequest {
  readonly projectDetailRequest: ProjectDetailRequest;
}

/**
 * Request parameters for projectsCreate operation in ProjectsApi.
 */
export interface ProjectsApiProjectsCreateRequest {
  readonly projectDetailRequest: ProjectDetailRequest;
}

/**
 * Request parameters for projectsDestroy operation in ProjectsApi.
 */
export interface ProjectsApiProjectsDestroyRequest {
  /**
   * A unique integer value identifying this project.
   */
  readonly id: number;
}

/**
 * Request parameters for projectsList operation in ProjectsApi.
 */
export interface ProjectsApiProjectsListRequest {
  /**
   * A page number within the paginated result set.
   */
  readonly page?: number;
}

/**
 * Request parameters for projectsPartialUpdate operation in ProjectsApi.
 */
export interface ProjectsApiProjectsPartialUpdateRequest {
  /**
   * A unique integer value identifying this project.
   */
  readonly id: number;

  readonly patchedProjectDetailRequest?: PatchedProjectDetailRequest;
}

/**
 * Request parameters for projectsRetrieve operation in ProjectsApi.
 */
export interface ProjectsApiProjectsRetrieveRequest {
  /**
   * A unique integer value identifying this project.
   */
  readonly id: number;
}

/**
 * Request parameters for projectsUpdate operation in ProjectsApi.
 */
export interface ProjectsApiProjectsUpdateRequest {
  /**
   * A unique integer value identifying this project.
   */
  readonly id: number;

  readonly projectDetailRequest: ProjectDetailRequest;
}

/**
 * ProjectsApi - object-oriented interface
 */
export class ProjectsApi extends BaseAPI implements ProjectsApiInterface {
  /**
   *
   * @param {ProjectsApiProjectsBulkUpdateUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectsBulkUpdateUpdate(
    requestParameters: ProjectsApiProjectsBulkUpdateUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectsApiFp(this.configuration)
      .projectsBulkUpdateUpdate(requestParameters.projectDetailRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectsApiProjectsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectsCreate(
    requestParameters: ProjectsApiProjectsCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectsApiFp(this.configuration)
      .projectsCreate(requestParameters.projectDetailRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectsApiProjectsDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectsDestroy(
    requestParameters: ProjectsApiProjectsDestroyRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectsApiFp(this.configuration)
      .projectsDestroy(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectsApiProjectsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectsList(
    requestParameters: ProjectsApiProjectsListRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectsApiFp(this.configuration)
      .projectsList(requestParameters.page, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectsApiProjectsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectsPartialUpdate(
    requestParameters: ProjectsApiProjectsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectsApiFp(this.configuration)
      .projectsPartialUpdate(
        requestParameters.id,
        requestParameters.patchedProjectDetailRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectsApiProjectsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectsRetrieve(
    requestParameters: ProjectsApiProjectsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectsApiFp(this.configuration)
      .projectsRetrieve(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {ProjectsApiProjectsUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public projectsUpdate(
    requestParameters: ProjectsApiProjectsUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ProjectsApiFp(this.configuration)
      .projectsUpdate(
        requestParameters.id,
        requestParameters.projectDetailRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
