/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { PaginatedTagList } from "../models";
// @ts-ignore
import type { PatchedTagRequest } from "../models";
// @ts-ignore
import type { Tag } from "../models";
// @ts-ignore
import type { TagDetail } from "../models";
// @ts-ignore
import type { TagRequest } from "../models";
/**
 * TagsApi - axios parameter creator
 */
export const TagsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {TagRequest} tagRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsCreate: async (
      tagRequest: TagRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'tagRequest' is not null or undefined
      assertParamExists("tagsCreate", "tagRequest", tagRequest);
      const localVarPath = `/api/tags/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        tagRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsDestroy: async (
      slug: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'slug' is not null or undefined
      assertParamExists("tagsDestroy", "slug", slug);
      const localVarPath = `/api/tags/{slug}/`.replace(
        `{${"slug"}}`,
        encodeURIComponent(String(slug)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsList: async (
      page?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/tags/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} slug
     * @param {PatchedTagRequest} [patchedTagRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsPartialUpdate: async (
      slug: string,
      patchedTagRequest?: PatchedTagRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'slug' is not null or undefined
      assertParamExists("tagsPartialUpdate", "slug", slug);
      const localVarPath = `/api/tags/{slug}/`.replace(
        `{${"slug"}}`,
        encodeURIComponent(String(slug)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        patchedTagRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsRetrieve: async (
      slug: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'slug' is not null or undefined
      assertParamExists("tagsRetrieve", "slug", slug);
      const localVarPath = `/api/tags/{slug}/`.replace(
        `{${"slug"}}`,
        encodeURIComponent(String(slug)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} slug
     * @param {TagRequest} tagRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsUpdate: async (
      slug: string,
      tagRequest: TagRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'slug' is not null or undefined
      assertParamExists("tagsUpdate", "slug", slug);
      // verify required parameter 'tagRequest' is not null or undefined
      assertParamExists("tagsUpdate", "tagRequest", tagRequest);
      const localVarPath = `/api/tags/{slug}/`.replace(
        `{${"slug"}}`,
        encodeURIComponent(String(slug)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      // authentication E2ETestBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        tagRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TagsApi - functional programming interface
 */
export const TagsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TagsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {TagRequest} tagRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tagsCreate(
      tagRequest: TagRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Tag>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tagsCreate(
        tagRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TagsApi.tagsCreate"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tagsDestroy(
      slug: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tagsDestroy(
        slug,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TagsApi.tagsDestroy"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tagsList(
      page?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PaginatedTagList>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tagsList(
        page,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TagsApi.tagsList"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} slug
     * @param {PatchedTagRequest} [patchedTagRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tagsPartialUpdate(
      slug: string,
      patchedTagRequest?: PatchedTagRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Tag>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.tagsPartialUpdate(
          slug,
          patchedTagRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TagsApi.tagsPartialUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tagsRetrieve(
      slug: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TagDetail>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tagsRetrieve(
        slug,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TagsApi.tagsRetrieve"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} slug
     * @param {TagRequest} tagRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tagsUpdate(
      slug: string,
      tagRequest: TagRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Tag>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tagsUpdate(
        slug,
        tagRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TagsApi.tagsUpdate"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * TagsApi - factory interface
 */
export const TagsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = TagsApiFp(configuration);
  return {
    /**
     *
     * @param {TagsApiTagsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsCreate(
      requestParameters: TagsApiTagsCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Tag> {
      return localVarFp
        .tagsCreate(requestParameters.tagRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TagsApiTagsDestroyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsDestroy(
      requestParameters: TagsApiTagsDestroyRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .tagsDestroy(requestParameters.slug, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TagsApiTagsListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsList(
      requestParameters: TagsApiTagsListRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedTagList> {
      return localVarFp
        .tagsList(requestParameters.page, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TagsApiTagsPartialUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsPartialUpdate(
      requestParameters: TagsApiTagsPartialUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Tag> {
      return localVarFp
        .tagsPartialUpdate(
          requestParameters.slug,
          requestParameters.patchedTagRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TagsApiTagsRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsRetrieve(
      requestParameters: TagsApiTagsRetrieveRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TagDetail> {
      return localVarFp
        .tagsRetrieve(requestParameters.slug, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TagsApiTagsUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tagsUpdate(
      requestParameters: TagsApiTagsUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Tag> {
      return localVarFp
        .tagsUpdate(
          requestParameters.slug,
          requestParameters.tagRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TagsApi - interface
 */
export interface TagsApiInterface {
  /**
   *
   * @param {TagsApiTagsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tagsCreate(
    requestParameters: TagsApiTagsCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Tag>;

  /**
   *
   * @param {TagsApiTagsDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tagsDestroy(
    requestParameters: TagsApiTagsDestroyRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<void>;

  /**
   *
   * @param {TagsApiTagsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tagsList(
    requestParameters?: TagsApiTagsListRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PaginatedTagList>;

  /**
   *
   * @param {TagsApiTagsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tagsPartialUpdate(
    requestParameters: TagsApiTagsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Tag>;

  /**
   *
   * @param {TagsApiTagsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tagsRetrieve(
    requestParameters: TagsApiTagsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<TagDetail>;

  /**
   *
   * @param {TagsApiTagsUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tagsUpdate(
    requestParameters: TagsApiTagsUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Tag>;
}

/**
 * Request parameters for tagsCreate operation in TagsApi.
 */
export interface TagsApiTagsCreateRequest {
  readonly tagRequest: TagRequest;
}

/**
 * Request parameters for tagsDestroy operation in TagsApi.
 */
export interface TagsApiTagsDestroyRequest {
  readonly slug: string;
}

/**
 * Request parameters for tagsList operation in TagsApi.
 */
export interface TagsApiTagsListRequest {
  /**
   * A page number within the paginated result set.
   */
  readonly page?: number;
}

/**
 * Request parameters for tagsPartialUpdate operation in TagsApi.
 */
export interface TagsApiTagsPartialUpdateRequest {
  readonly slug: string;

  readonly patchedTagRequest?: PatchedTagRequest;
}

/**
 * Request parameters for tagsRetrieve operation in TagsApi.
 */
export interface TagsApiTagsRetrieveRequest {
  readonly slug: string;
}

/**
 * Request parameters for tagsUpdate operation in TagsApi.
 */
export interface TagsApiTagsUpdateRequest {
  readonly slug: string;

  readonly tagRequest: TagRequest;
}

/**
 * TagsApi - object-oriented interface
 */
export class TagsApi extends BaseAPI implements TagsApiInterface {
  /**
   *
   * @param {TagsApiTagsCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tagsCreate(
    requestParameters: TagsApiTagsCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TagsApiFp(this.configuration)
      .tagsCreate(requestParameters.tagRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TagsApiTagsDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tagsDestroy(
    requestParameters: TagsApiTagsDestroyRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TagsApiFp(this.configuration)
      .tagsDestroy(requestParameters.slug, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TagsApiTagsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tagsList(
    requestParameters: TagsApiTagsListRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return TagsApiFp(this.configuration)
      .tagsList(requestParameters.page, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TagsApiTagsPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tagsPartialUpdate(
    requestParameters: TagsApiTagsPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TagsApiFp(this.configuration)
      .tagsPartialUpdate(
        requestParameters.slug,
        requestParameters.patchedTagRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TagsApiTagsRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tagsRetrieve(
    requestParameters: TagsApiTagsRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TagsApiFp(this.configuration)
      .tagsRetrieve(requestParameters.slug, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TagsApiTagsUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tagsUpdate(
    requestParameters: TagsApiTagsUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TagsApiFp(this.configuration)
      .tagsUpdate(requestParameters.slug, requestParameters.tagRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
