/* tslint:disable */
/* eslint-disable */
/**
 * UPOU TODO API
 * Planner-first productivity API for UPOU faculty and staff
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { PaginatedTaskList } from "../models";
// @ts-ignore
import type { PatchedTaskRequest } from "../models";
// @ts-ignore
import type { Task } from "../models";
// @ts-ignore
import type { TaskRequest } from "../models";
/**
 * TasksApi - axios parameter creator
 */
export const TasksApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {PatchedTaskRequest} [patchedTaskRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksBulkUpdatePartialUpdate: async (
      patchedTaskRequest?: PatchedTaskRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/tasks/bulk_update/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        patchedTaskRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {TaskRequest} taskRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksBulkUpdateUpdate: async (
      taskRequest: TaskRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'taskRequest' is not null or undefined
      assertParamExists("tasksBulkUpdateUpdate", "taskRequest", taskRequest);
      const localVarPath = `/api/tasks/bulk_update/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        taskRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {TaskRequest} taskRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksCreate: async (
      taskRequest: TaskRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'taskRequest' is not null or undefined
      assertParamExists("tasksCreate", "taskRequest", taskRequest);
      const localVarPath = `/api/tasks/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        taskRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksDestroy: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("tasksDestroy", "id", id);
      const localVarPath = `/api/tasks/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {TaskRequest} taskRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksDuplicateCreate: async (
      id: number,
      taskRequest: TaskRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("tasksDuplicateCreate", "id", id);
      // verify required parameter 'taskRequest' is not null or undefined
      assertParamExists("tasksDuplicateCreate", "taskRequest", taskRequest);
      const localVarPath = `/api/tasks/{id}/duplicate/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        taskRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} [endDate]
     * @param {boolean} [inbox]
     * @param {string} [ordering] Which field to use when ordering the results.
     * @param {number} [page] A page number within the paginated result set.
     * @param {string} [startDate]
     * @param {string} [tag]
     * @param {boolean} [today]
     * @param {boolean} [upcoming]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksList: async (
      endDate?: string,
      inbox?: boolean,
      ordering?: string,
      page?: number,
      startDate?: string,
      tag?: string,
      today?: boolean,
      upcoming?: boolean,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/tasks/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (endDate !== undefined) {
        localVarQueryParameter["end_date"] =
          (endDate as any) instanceof Date
            ? (endDate as any).toISOString().substring(0, 10)
            : endDate;
      }

      if (inbox !== undefined) {
        localVarQueryParameter["inbox"] = inbox;
      }

      if (ordering !== undefined) {
        localVarQueryParameter["ordering"] = ordering;
      }

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      if (startDate !== undefined) {
        localVarQueryParameter["start_date"] =
          (startDate as any) instanceof Date
            ? (startDate as any).toISOString().substring(0, 10)
            : startDate;
      }

      if (tag !== undefined) {
        localVarQueryParameter["tag"] = tag;
      }

      if (today !== undefined) {
        localVarQueryParameter["today"] = today;
      }

      if (upcoming !== undefined) {
        localVarQueryParameter["upcoming"] = upcoming;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {PatchedTaskRequest} [patchedTaskRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksPartialUpdate: async (
      id: number,
      patchedTaskRequest?: PatchedTaskRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("tasksPartialUpdate", "id", id);
      const localVarPath = `/api/tasks/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        patchedTaskRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksRetrieve: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("tasksRetrieve", "id", id);
      const localVarPath = `/api/tasks/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {TaskRequest} taskRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksUpdate: async (
      id: number,
      taskRequest: TaskRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("tasksUpdate", "id", id);
      // verify required parameter 'taskRequest' is not null or undefined
      assertParamExists("tasksUpdate", "taskRequest", taskRequest);
      const localVarPath = `/api/tasks/{id}/`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication cookieAuth required

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        taskRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TasksApi - functional programming interface
 */
export const TasksApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TasksApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {PatchedTaskRequest} [patchedTaskRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tasksBulkUpdatePartialUpdate(
      patchedTaskRequest?: PatchedTaskRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.tasksBulkUpdatePartialUpdate(
          patchedTaskRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TasksApi.tasksBulkUpdatePartialUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {TaskRequest} taskRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tasksBulkUpdateUpdate(
      taskRequest: TaskRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.tasksBulkUpdateUpdate(
          taskRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TasksApi.tasksBulkUpdateUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {TaskRequest} taskRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tasksCreate(
      taskRequest: TaskRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tasksCreate(
        taskRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TasksApi.tasksCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tasksDestroy(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tasksDestroy(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TasksApi.tasksDestroy"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {TaskRequest} taskRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tasksDuplicateCreate(
      id: number,
      taskRequest: TaskRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.tasksDuplicateCreate(
          id,
          taskRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TasksApi.tasksDuplicateCreate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} [endDate]
     * @param {boolean} [inbox]
     * @param {string} [ordering] Which field to use when ordering the results.
     * @param {number} [page] A page number within the paginated result set.
     * @param {string} [startDate]
     * @param {string} [tag]
     * @param {boolean} [today]
     * @param {boolean} [upcoming]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tasksList(
      endDate?: string,
      inbox?: boolean,
      ordering?: string,
      page?: number,
      startDate?: string,
      tag?: string,
      today?: boolean,
      upcoming?: boolean,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PaginatedTaskList>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tasksList(
        endDate,
        inbox,
        ordering,
        page,
        startDate,
        tag,
        today,
        upcoming,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TasksApi.tasksList"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {PatchedTaskRequest} [patchedTaskRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tasksPartialUpdate(
      id: number,
      patchedTaskRequest?: PatchedTaskRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.tasksPartialUpdate(
          id,
          patchedTaskRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TasksApi.tasksPartialUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tasksRetrieve(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tasksRetrieve(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TasksApi.tasksRetrieve"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {number} id A unique integer value identifying this task.
     * @param {TaskRequest} taskRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async tasksUpdate(
      id: number,
      taskRequest: TaskRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tasksUpdate(
        id,
        taskRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TasksApi.tasksUpdate"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * TasksApi - factory interface
 */
export const TasksApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = TasksApiFp(configuration);
  return {
    /**
     *
     * @param {TasksApiTasksBulkUpdatePartialUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksBulkUpdatePartialUpdate(
      requestParameters: TasksApiTasksBulkUpdatePartialUpdateRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Task> {
      return localVarFp
        .tasksBulkUpdatePartialUpdate(
          requestParameters.patchedTaskRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TasksApiTasksBulkUpdateUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksBulkUpdateUpdate(
      requestParameters: TasksApiTasksBulkUpdateUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Task> {
      return localVarFp
        .tasksBulkUpdateUpdate(requestParameters.taskRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TasksApiTasksCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksCreate(
      requestParameters: TasksApiTasksCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Task> {
      return localVarFp
        .tasksCreate(requestParameters.taskRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TasksApiTasksDestroyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksDestroy(
      requestParameters: TasksApiTasksDestroyRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .tasksDestroy(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TasksApiTasksDuplicateCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksDuplicateCreate(
      requestParameters: TasksApiTasksDuplicateCreateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Task> {
      return localVarFp
        .tasksDuplicateCreate(
          requestParameters.id,
          requestParameters.taskRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TasksApiTasksListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksList(
      requestParameters: TasksApiTasksListRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedTaskList> {
      return localVarFp
        .tasksList(
          requestParameters.endDate,
          requestParameters.inbox,
          requestParameters.ordering,
          requestParameters.page,
          requestParameters.startDate,
          requestParameters.tag,
          requestParameters.today,
          requestParameters.upcoming,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TasksApiTasksPartialUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksPartialUpdate(
      requestParameters: TasksApiTasksPartialUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Task> {
      return localVarFp
        .tasksPartialUpdate(
          requestParameters.id,
          requestParameters.patchedTaskRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TasksApiTasksRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksRetrieve(
      requestParameters: TasksApiTasksRetrieveRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Task> {
      return localVarFp
        .tasksRetrieve(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TasksApiTasksUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tasksUpdate(
      requestParameters: TasksApiTasksUpdateRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Task> {
      return localVarFp
        .tasksUpdate(
          requestParameters.id,
          requestParameters.taskRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TasksApi - interface
 */
export interface TasksApiInterface {
  /**
   *
   * @param {TasksApiTasksBulkUpdatePartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tasksBulkUpdatePartialUpdate(
    requestParameters?: TasksApiTasksBulkUpdatePartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Task>;

  /**
   *
   * @param {TasksApiTasksBulkUpdateUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tasksBulkUpdateUpdate(
    requestParameters: TasksApiTasksBulkUpdateUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Task>;

  /**
   *
   * @param {TasksApiTasksCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tasksCreate(
    requestParameters: TasksApiTasksCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Task>;

  /**
   *
   * @param {TasksApiTasksDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tasksDestroy(
    requestParameters: TasksApiTasksDestroyRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<void>;

  /**
   *
   * @param {TasksApiTasksDuplicateCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tasksDuplicateCreate(
    requestParameters: TasksApiTasksDuplicateCreateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Task>;

  /**
   *
   * @param {TasksApiTasksListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tasksList(
    requestParameters?: TasksApiTasksListRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<PaginatedTaskList>;

  /**
   *
   * @param {TasksApiTasksPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tasksPartialUpdate(
    requestParameters: TasksApiTasksPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Task>;

  /**
   *
   * @param {TasksApiTasksRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tasksRetrieve(
    requestParameters: TasksApiTasksRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Task>;

  /**
   *
   * @param {TasksApiTasksUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  tasksUpdate(
    requestParameters: TasksApiTasksUpdateRequest,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Task>;
}

/**
 * Request parameters for tasksBulkUpdatePartialUpdate operation in TasksApi.
 */
export interface TasksApiTasksBulkUpdatePartialUpdateRequest {
  readonly patchedTaskRequest?: PatchedTaskRequest;
}

/**
 * Request parameters for tasksBulkUpdateUpdate operation in TasksApi.
 */
export interface TasksApiTasksBulkUpdateUpdateRequest {
  readonly taskRequest: TaskRequest;
}

/**
 * Request parameters for tasksCreate operation in TasksApi.
 */
export interface TasksApiTasksCreateRequest {
  readonly taskRequest: TaskRequest;
}

/**
 * Request parameters for tasksDestroy operation in TasksApi.
 */
export interface TasksApiTasksDestroyRequest {
  /**
   * A unique integer value identifying this task.
   */
  readonly id: number;
}

/**
 * Request parameters for tasksDuplicateCreate operation in TasksApi.
 */
export interface TasksApiTasksDuplicateCreateRequest {
  /**
   * A unique integer value identifying this task.
   */
  readonly id: number;

  readonly taskRequest: TaskRequest;
}

/**
 * Request parameters for tasksList operation in TasksApi.
 */
export interface TasksApiTasksListRequest {
  readonly endDate?: string;

  readonly inbox?: boolean;

  /**
   * Which field to use when ordering the results.
   */
  readonly ordering?: string;

  /**
   * A page number within the paginated result set.
   */
  readonly page?: number;

  readonly startDate?: string;

  readonly tag?: string;

  readonly today?: boolean;

  readonly upcoming?: boolean;
}

/**
 * Request parameters for tasksPartialUpdate operation in TasksApi.
 */
export interface TasksApiTasksPartialUpdateRequest {
  /**
   * A unique integer value identifying this task.
   */
  readonly id: number;

  readonly patchedTaskRequest?: PatchedTaskRequest;
}

/**
 * Request parameters for tasksRetrieve operation in TasksApi.
 */
export interface TasksApiTasksRetrieveRequest {
  /**
   * A unique integer value identifying this task.
   */
  readonly id: number;
}

/**
 * Request parameters for tasksUpdate operation in TasksApi.
 */
export interface TasksApiTasksUpdateRequest {
  /**
   * A unique integer value identifying this task.
   */
  readonly id: number;

  readonly taskRequest: TaskRequest;
}

/**
 * TasksApi - object-oriented interface
 */
export class TasksApi extends BaseAPI implements TasksApiInterface {
  /**
   *
   * @param {TasksApiTasksBulkUpdatePartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tasksBulkUpdatePartialUpdate(
    requestParameters: TasksApiTasksBulkUpdatePartialUpdateRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return TasksApiFp(this.configuration)
      .tasksBulkUpdatePartialUpdate(
        requestParameters.patchedTaskRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TasksApiTasksBulkUpdateUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tasksBulkUpdateUpdate(
    requestParameters: TasksApiTasksBulkUpdateUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TasksApiFp(this.configuration)
      .tasksBulkUpdateUpdate(requestParameters.taskRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TasksApiTasksCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tasksCreate(
    requestParameters: TasksApiTasksCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TasksApiFp(this.configuration)
      .tasksCreate(requestParameters.taskRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TasksApiTasksDestroyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tasksDestroy(
    requestParameters: TasksApiTasksDestroyRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TasksApiFp(this.configuration)
      .tasksDestroy(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TasksApiTasksDuplicateCreateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tasksDuplicateCreate(
    requestParameters: TasksApiTasksDuplicateCreateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TasksApiFp(this.configuration)
      .tasksDuplicateCreate(
        requestParameters.id,
        requestParameters.taskRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TasksApiTasksListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tasksList(
    requestParameters: TasksApiTasksListRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return TasksApiFp(this.configuration)
      .tasksList(
        requestParameters.endDate,
        requestParameters.inbox,
        requestParameters.ordering,
        requestParameters.page,
        requestParameters.startDate,
        requestParameters.tag,
        requestParameters.today,
        requestParameters.upcoming,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TasksApiTasksPartialUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tasksPartialUpdate(
    requestParameters: TasksApiTasksPartialUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TasksApiFp(this.configuration)
      .tasksPartialUpdate(
        requestParameters.id,
        requestParameters.patchedTaskRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TasksApiTasksRetrieveRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tasksRetrieve(
    requestParameters: TasksApiTasksRetrieveRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TasksApiFp(this.configuration)
      .tasksRetrieve(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TasksApiTasksUpdateRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public tasksUpdate(
    requestParameters: TasksApiTasksUpdateRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return TasksApiFp(this.configuration)
      .tasksUpdate(requestParameters.id, requestParameters.taskRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
