# Generated by Django 5.1.7 on 2025-04-03 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upoutodo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["order", "-due_date", "priority", "completion_date"]},
        ),
    ]
