# Generated by Django 5.1.7 on 2025-05-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upoutodo", "0004_alter_task_completion_date_alter_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
