# Generated by Django 5.1.7 on 2025-06-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upoutodo", "0006_task_created_at_task_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                default="system",
                max_length=6,
            ),
        ),
    ]
