# Generated by Django 5.2.5 on 2025-09-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upoutodo', '0007_userprofile_is_onboarded_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rrule',
            field=models.TextField(blank=True, help_text='RRULE string for recurring tasks', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Manila', help_text="User's timezone (e.g., Asia/Manila, America/New_York)", max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Next due date (cached from rrule)', null=True),
        ),
    ]
