# Generated by Django 5.2.5 on 2025-08-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upoutodo", "0007_userprofile_is_onboarded_userprofile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notification_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for notifications. If not set, uses the user's login email.",
                max_length=254,
                null=True,
            ),
        ),
    ]
