# Generated by Django 5.2.5 on 2025-10-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upoutodo", "0007_userprofile_is_onboarded_userprofile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="anchor_mode",
            field=models.CharField(
                blank=True,
                choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed")],
                help_text="How to anchor recurring task instances",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="dtstart",
            field=models.DateTimeField(
                blank=True, help_text="Start date for recurrence", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="rrule",
            field=models.TextField(
                blank=True, help_text="RRule string for recurring tasks", null=True
            ),
        ),
    ]
