# Generated by Django 5.2.5 on 2025-10-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upoutodo", "0007_userprofile_is_onboarded_userprofile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dtstart",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="rrule",
            field=models.TextField(blank=True, null=True),
        ),
    ]
