# Generated by Django 5.2.5 on 2025-10-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upoutodo", "0008_task_dtstart_task_rrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="anchor_mode",
            field=models.CharField(
                blank=True,
                choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="dtstart",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="rrule",
            field=models.TextField(blank=True, null=True),
        ),
    ]
