# Generated by Django 5.2.5 on 2025-08-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upoutodo', '0008_add_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='upoutodo.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_anchor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_timezone',
            field=models.CharField(default='Asia/Manila', max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_when_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rrule',
            field=models.TextField(blank=True),
        ),
    ]
