# Generated by Django 5.2.5 on 2025-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upoutodo', '0009_add_recurrence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_anchor_mode',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled date'), ('COMPLETED', 'Completed date')], default='SCHEDULED', max_length=10),
        ),
    ]
