# Generated by Django 5.2.5 on 2025-11-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upoutodo", "0009_alter_task_anchor_mode_alter_task_dtstart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="anchor_mode",
            field=models.CharField(
                blank=True,
                choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="rrule",
            field=models.TextField(blank=True, default=""),
        ),
    ]
