# Generated by Django 5.2.5 on 2026-06-26 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upoutodo", "0011_add_notification_model_and_email_digest_pref"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "energy_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("available_minutes", models.PositiveIntegerField(default=120)),
                (
                    "focus_mode",
                    models.CharField(
                        choices=[
                            ("flexible", "Flexible"),
                            ("deep", "Deep Work"),
                            ("admin", "Admin"),
                            ("light", "Light Work"),
                        ],
                        default="flexible",
                        max_length=10,
                    ),
                ),
                ("context", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TodayPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "check_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="today_plans",
                        to="upoutodo.energycheckin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="today_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField(blank=True, default="")),
                ("estimated_minutes", models.PositiveIntegerField(default=30)),
                ("score", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("accepted", "Accepted"),
                            ("snoozed", "Snoozed"),
                            ("dismissed", "Dismissed"),
                            ("done", "Done"),
                        ],
                        default="suggested",
                        max_length=10,
                    ),
                ),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="upoutodo.task",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="upoutodo.todayplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-score", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="energycheckin",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_energy_check_in_per_user_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="todayplan",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_today_plan_per_user_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="planitem",
            constraint=models.UniqueConstraint(
                fields=("plan", "task"), name="unique_plan_item_per_plan_task"
            ),
        ),
    ]
