# Generated by Django 5.2.5 on 2025-09-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upoutodo', '0011_populate_due_date_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rrule',
            field=models.TextField(blank=True, help_text='RRULE string for recurring tasks', null=True),
        ),
    ]
