# Generated by Django 5.2.5 on 2026-06-27 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upoutodo", "0012_energycheckin_todayplan_planitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TodayPlanFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("helpfulness_rating", models.PositiveSmallIntegerField()),
                ("confidence_rating", models.PositiveSmallIntegerField()),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="upoutodo.todayplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="today_plan_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("helpfulness_rating__gte", 1),
                            ("helpfulness_rating__lte", 5),
                        ),
                        name="today_plan_feedback_helpfulness_between_1_and_5",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence_rating__gte", 1), ("confidence_rating__lte", 5)
                        ),
                        name="today_plan_feedback_confidence_between_1_and_5",
                    ),
                ],
            },
        ),
    ]
